name: Deploy Spring Boot to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: mvn clean package -DskipTests

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: purchase-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/demo-0.0.1-SNAPSHOT.jar