name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'   # 🔥 keep 17
          distribution: 'temurin'
          cache: maven        # 🚀 speeds up builds

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: List target files (debug)
        run: ls -la target

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: purchase-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar